module.exports = {
  providerTypes: {
    GITHUB: "GITHUB",
    GITLAB: "GITLAB",
    NPM: "NPM",
    PIP: "PIP",
    CODECOV: "CODECOV",
    COVERALLS: "COVERALLS",
    PYTHON: "PYTHON",
    NODEJS: "NODEJS",
    TRAVIS: "TRAVIS",
    CIRCLECI: "CIRCLECI",
    APPVEYOR: "APPVEYOR",
    DISCORD: "DISCORD",
    SPECTRUM: "SPECTRUM",
    GITTER: "GITTER",
  },
  badgeTypes: {
    BUILD: "build",
    COVERAGE: "coverage",
    DEPENDANCIES: "dependancies",
    DOWNLOADS: "downloads",
    GH_FORK: "ghFork",
    GH_STAR: "ghStar",
    ALL_CONTRIBUTERS: "allContributers",
    CODE_OF_CONDUCT: "codeOfConduct",
    LICENSE: "license",
    SIZE: "size",
    VERSION: "version",
  },
};
