module.exports = {
    GITHUB: 'GITHUB',
    GITLAB: 'GITLAB',
    NPM: 'NPM',
    PIP: 'PIP',
    CODECOV: 'CODECOV',
    COVERALLS: 'COVERALLS',
    PYTHON: 'PYTHON',
    NODEJS: 'NODEJS',
    TRAVIS: 'TRAVIS',
    CIRCLECI: 'CIRCLECI',
    APPVEYOR: 'APPVEYOR',
	DISCORD: 'DISCORD',
    SPECTRUM: 'SPECTRUM',
    GITTER: "GITTER"
}
